package org.test.automation.core;

import java.util.Collections;
import java.util.List;

import org.apache.log4j.Logger;


/**
* <p>
* This class is to represent each full test case in a .atc file.
* </p>
* 
* <p>
* It is used for both the running of the tests and the generating of the report
* after. This class is generated by
* {@link org.test.automation.core.AutomatedTestCaseRunner} when it reads the
* test cases.
*/
public final class TestCase {
	
	private final static Logger LOGGER = Logger.getLogger(TestCase.class);
	
	private final String name;
	
	private final List<TestCall> methods;


	TestCase(final String name, final List<TestCall> methods)
	{
		this.name = name;
		this.methods = Collections.unmodifiableList(methods);
	}

	/**The name of the test case
	 * @return the name of the test case
	 */
	public String getName()
	{
		return name;
	}
	
	/**The list of test calls that will be made by this test case
	 * @return list of test calls that will be made by this test case this can't be altered
	 */
	public List<TestCall> getTestCalls()
	{
		return Collections.unmodifiableList(methods);
	}

	/**
	 * This executes the test calls in the order from the .atc file
	 */
	public void runTestCase()
	{
		LOGGER.trace("ENTER:runTestCase()");
		for (TestCall method : methods)
		{
			method.runCommand();
			
			if(!method.getResult().isSuccesfull())
			{
				break;
			}

		}
		LOGGER.trace("EXIT:runTestCase()");
	}

}
